# Consolidacion de la Informacion

In [1]:
import pandas as pd

In [2]:
info_ind = pd.read_csv(r"C:\Users\pasal\Universidad EAFIT\Ing Mats in Data Science - General\datasets\indicadores_anual.csv", sep = ';')
info_gv = pd.read_csv(r"C:\Users\pasal\Google Drive\EAFIT\Ciencia de Datos y Analitica\02 Segundo Semestre\Metodos Estadisticos Avanzados\Trabajo Final\metodos-estadisticos-avanzados\PreparacionDatos\Costos_Gastos_ventas.csv")
info_gv = info_gv.rename(columns = {'AÃ±o':'YEAR'})
info_gv['YEAR'] = info_gv['YEAR'].astype(int)

In [3]:
info_ind['YEAR'] = info_ind['PERIODO'].apply(lambda x: x.split('/')[2])
info_ind['YEAR'] = info_ind['YEAR'].astype(int)
info_indicadores = pd.pivot_table(info_ind, index = 'YEAR', values = 'VALOR', columns = 'INDICADOR', aggfunc='sum').reset_index()

In [4]:
info_indicadores

INDICADOR,YEAR,balance fiscal,cuenta corriente,desempleo,inflacion,pib,tasa intervencion,tasa ocupacion,trm
0,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,638.61
1,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,737.98
2,1993,NaN,NaN,NaN,0.0380,NaN,NaN,NaN,804.33
3,1994,NaN,NaN,NaN,0.0318,NaN,NaN,NaN,831.27
4,1995,NaN,NaN,NaN,0.0409,NaN,NaN,NaN,987.65
5,1996,NaN,NaN,NaN,0.0575,NaN,NaN,NaN,1005.33
6,1997,NaN,NaN,NaN,0.0677,NaN,NaN,NaN,1293.58
7,1998,NaN,NaN,NaN,0.0366,NaN,NaN,NaN,1542.11
8,1999,NaN,NaN,NaN,0.0194,NaN,0.1200,NaN,1873.77
9,2000,NaN,300.324085,NaN,0.0244,NaN,0.1200,NaN,2229.18
10,2001,NaN,-248.407545,0.138393,0.0373,NaN,0.0850,NaN,2291.18
11,2002,NaN,-402.192926,0.157730,0.0317,NaN,0.0525,0.525643,2864.79
12,2003,NaN,-312.769123,0.121856,0.0200,NaN,0.0725,0.539597,2778.21
13,2004,NaN,-71.352263,0.120707,0.0767,NaN,0.0650,0.530749,2389.75
14,2005,193103.6293,-250.972281,0.103344,0.0569,337958.000,0.0600,0.533837,2284.22
15,2006,235474.0372,-829.880444,0.117828,0.0448,381604.000,0.0750,0.520096,2238.79
16,2007,266481.3548,-1106.245659,0.098939,0.0485,428506.000,0.0950,0.517742,2014.76
17,2008,264277.4423,-2346.138293,0.106068,0.0550,476554.000,0.0950,0.519135,2243.59
18,2009,284663.7705,-1488.161589,0.113115,0.0649,501574.000,0.0350,0.539315,2044.23
19,2010,301035.2333,-2695.053083,0.111200,0.0699,544060.000,0.0300,0.553599,1913.98
20,2011,346409.1536,-2972.356506,0.098176,0.0765,619023.000,0.0475,0.567962,1942.70
21,2012,388413.2463,-2920.627410,0.095508,0.0875,666507.000,0.0425,0.578418,1768.23
22,2013,417454.1234,-3172.588911,0.084422,0.0923,714093.000,0.0325,0.579734,1926.83
23,2014,451080.6363,-6452.434228,0.087229,0.1670,762903.000,0.0450,0.583909,2392.46
24,2015,439096.9531,-3802.922145,0.085889,0.1768,804692.000,0.0575,0.589602,3149.47
25,2016,483076.4028,-2541.405317,0.087428,0.2163,863782.000,0.0750,0.585346,3000.71
26,2017,501725.7063,-1529.008656,0.086274,0.1946,920471.000,0.0475,0.583539,2984.00
27,2018,596327.1323,-3740.195297,0.097211,0.2259,985931.000,0.0425,0.577860,3249.75
28,2019,NaN,-3522.592957,0.095317,0.2260,1062342.495,0.0425,NaN,3277.14

In [5]:
all_data = info_gv.merge(info_indicadores, how = 'left', on = 'YEAR').drop(columns = ['tasa ocupacion'])

In [6]:
new_cols = []
for col in all_data.columns.values:
    new_cols.append(col.replace(' ','_'))
    
all_data.columns = new_cols

In [7]:
all_data.to_csv('Data/consolidado_info.csv', index = False, sep = ',')
all_data.to_csv('C:/Users/pasal/Universidad EAFIT/Ing Mats in Data Science - General/datasets/consolidado_info.csv', index = False, sep = ',')

In [8]:
all_data

,NIT,YEAR,Costo_de_ventas,Gastos_de_ventas,Costo_de_ventas_dif,Gastos_de_ventas_dif,balance_fiscal,cuenta_corriente,desempleo,inflacion,pib,tasa_intervencion,trm
0,800015615,2016,60626083.0,13978834.0,-6644631.0,1713101.0,483076.4028,-2541.405317,0.087428,0.2163,863782.0,0.0750,3000.71
1,800045720,2016,3785517.0,60608.0,261398.0,14912.0,483076.4028,-2541.405317,0.087428,0.2163,863782.0,0.0750,3000.71
2,800081030,2016,39634059.0,5645885.0,10012929.0,2314426.0,483076.4028,-2541.405317,0.087428,0.2163,863782.0,0.0750,3000.71
3,800112440,2016,24304534.0,8977594.0,-1366318.0,-337547.0,483076.4028,-2541.405317,0.087428,0.2163,863782.0,0.0750,3000.71
4,800118660,2016,31280967.0,6702215.0,-1538082.0,-1439109.0,483076.4028,-2541.405317,0.087428,0.2163,863782.0,0.0750,3000.71
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,900234565,2018,48454520.0,6727499.0,-5758426.0,1913877.0,596327.1323,-3740.195297,0.097211,0.2259,985931.0,0.0425,3249.75
95,900364670,2018,13653296.0,208080.0,-6188792.0,-165564.0,596327.1323,-3740.195297,0.097211,0.2259,985931.0,0.0425,3249.75
96,900378893,2018,169567783.0,8326660.0,-4439087.0,2066635.0,596327.1323,-3740.195297,0.097211,0.2259,985931.0,0.0425,3249.75
97,900389088,2018,6880597.0,166062.0,-1832745.0,2356.0,596327.1323,-3740.195297,0.097211,0.2259,985931.0,0.0425,3249.75
98,900437650,2018,8351676.0,5112417.0,-813980.0,464475.0,596327.1323,-3740.195297,0.097211,0.2259,985931.0,0.0425,3249.75